// Generated from the FIFA World Cup 2026 Regulations, Annex C
// Source reference: https://digitalhub.fifa.com/m/636f5c9c6f29771f/original/FWC2026_regulations_EN.pdf
// Key: advancing third-placed groups sorted alphabetically.
// Value order: 1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L opponents.
export const fifaThirdPlaceAllocationTable: Record<string, string> = {
  ABCDEFGH: 'HGBCAFDE', // Annex C option 495
  ABCDEFGI: 'CGBDAFEI', // Annex C option 494
  ABCDEFGJ: 'CGBDAFEJ', // Annex C option 493
  ABCDEFGK: 'CGBDAFEK', // Annex C option 492
  ABCDEFGL: 'CGBDAFLE', // Annex C option 491
  ABCDEFHI: 'HEBCAFDI', // Annex C option 490
  ABCDEFHJ: 'HJBCAFDE', // Annex C option 489
  ABCDEFHK: 'HEBCAFDK', // Annex C option 488
  ABCDEFHL: 'HFBCADLE', // Annex C option 487
  ABCDEFIJ: 'CJBDAFEI', // Annex C option 486
  ABCDEFIK: 'CEBDAFIK', // Annex C option 485
  ABCDEFIL: 'CEBDAFLI', // Annex C option 484
  ABCDEFJK: 'CJBDAFEK', // Annex C option 483
  ABCDEFJL: 'CJBDAFLE', // Annex C option 482
  ABCDEFKL: 'CEBDAFLK', // Annex C option 481
  ABCDEGHI: 'HGBCADEI', // Annex C option 480
  ABCDEGHJ: 'HGBCADEJ', // Annex C option 479
  ABCDEGHK: 'HGBCADEK', // Annex C option 478
  ABCDEGHL: 'HGBCADLE', // Annex C option 477
  ABCDEGIJ: 'EGBCADIJ', // Annex C option 476
  ABCDEGIK: 'EGBCADIK', // Annex C option 475
  ABCDEGIL: 'EGBCADLI', // Annex C option 474
  ABCDEGJK: 'EGBCADJK', // Annex C option 473
  ABCDEGJL: 'EGBCADLJ', // Annex C option 472
  ABCDEGKL: 'EGBCADLK', // Annex C option 471
  ABCDEHIJ: 'HJBCADEI', // Annex C option 470
  ABCDEHIK: 'HEBCADIK', // Annex C option 469
  ABCDEHIL: 'HEBCADLI', // Annex C option 468
  ABCDEHJK: 'HJBCADEK', // Annex C option 467
  ABCDEHJL: 'HJBCADLE', // Annex C option 466
  ABCDEHKL: 'HEBCADLK', // Annex C option 465
  ABCDEIJK: 'EJBCADIK', // Annex C option 464
  ABCDEIJL: 'EJBCADLI', // Annex C option 463
  ABCDEIKL: 'EIBCADLK', // Annex C option 462
  ABCDEJKL: 'EJBCADLK', // Annex C option 461
  ABCDFGHI: 'HGBCAFDI', // Annex C option 460
  ABCDFGHJ: 'HGBCAFDJ', // Annex C option 459
  ABCDFGHK: 'HGBCAFDK', // Annex C option 458
  ABCDFGHL: 'CGBDAFLH', // Annex C option 457
  ABCDFGIJ: 'CGBDAFIJ', // Annex C option 456
  ABCDFGIK: 'CGBDAFIK', // Annex C option 455
  ABCDFGIL: 'CGBDAFLI', // Annex C option 454
  ABCDFGJK: 'CGBDAFJK', // Annex C option 453
  ABCDFGJL: 'CGBDAFLJ', // Annex C option 452
  ABCDFGKL: 'CGBDAFLK', // Annex C option 451
  ABCDFHIJ: 'HJBCAFDI', // Annex C option 450
  ABCDFHIK: 'HFBCADIK', // Annex C option 449
  ABCDFHIL: 'HFBCADLI', // Annex C option 448
  ABCDFHJK: 'HJBCAFDK', // Annex C option 447
  ABCDFHJL: 'CJBDAFLH', // Annex C option 446
  ABCDFHKL: 'HFBCADLK', // Annex C option 445
  ABCDFIJK: 'CJBDAFIK', // Annex C option 444
  ABCDFIJL: 'CJBDAFLI', // Annex C option 443
  ABCDFIKL: 'CIBDAFLK', // Annex C option 442
  ABCDFJKL: 'CJBDAFLK', // Annex C option 441
  ABCDGHIJ: 'HGBCADIJ', // Annex C option 440
  ABCDGHIK: 'HGBCADIK', // Annex C option 439
  ABCDGHIL: 'HGBCADLI', // Annex C option 438
  ABCDGHJK: 'HGBCADJK', // Annex C option 437
  ABCDGHJL: 'HGBCADLJ', // Annex C option 436
  ABCDGHKL: 'HGBCADLK', // Annex C option 435
  ABCDGIJK: 'CJBDAGIK', // Annex C option 434
  ABCDGIJL: 'CJBDAGLI', // Annex C option 433
  ABCDGIKL: 'IGBCADLK', // Annex C option 432
  ABCDGJKL: 'CJBDAGLK', // Annex C option 431
  ABCDHIJK: 'HJBCADIK', // Annex C option 430
  ABCDHIJL: 'HJBCADLI', // Annex C option 429
  ABCDHIKL: 'HIBCADLK', // Annex C option 428
  ABCDHJKL: 'HJBCADLK', // Annex C option 427
  ABCDIJKL: 'IJBCADLK', // Annex C option 426
  ABCEFGHI: 'HGBCAFEI', // Annex C option 425
  ABCEFGHJ: 'HGBCAFEJ', // Annex C option 424
  ABCEFGHK: 'HGBCAFEK', // Annex C option 423
  ABCEFGHL: 'HGBCAFLE', // Annex C option 422
  ABCEFGIJ: 'EGBCAFIJ', // Annex C option 421
  ABCEFGIK: 'EGBCAFIK', // Annex C option 420
  ABCEFGIL: 'EGBCAFLI', // Annex C option 419
  ABCEFGJK: 'EGBCAFJK', // Annex C option 418
  ABCEFGJL: 'EGBCAFLJ', // Annex C option 417
  ABCEFGKL: 'EGBCAFLK', // Annex C option 416
  ABCEFHIJ: 'HJBCAFEI', // Annex C option 415
  ABCEFHIK: 'HEBCAFIK', // Annex C option 414
  ABCEFHIL: 'HEBCAFLI', // Annex C option 413
  ABCEFHJK: 'HJBCAFEK', // Annex C option 412
  ABCEFHJL: 'HJBCAFLE', // Annex C option 411
  ABCEFHKL: 'HEBCAFLK', // Annex C option 410
  ABCEFIJK: 'EJBCAFIK', // Annex C option 409
  ABCEFIJL: 'EJBCAFLI', // Annex C option 408
  ABCEFIKL: 'EIBCAFLK', // Annex C option 407
  ABCEFJKL: 'EJBCAFLK', // Annex C option 406
  ABCEGHIJ: 'HJBCAGEI', // Annex C option 405
  ABCEGHIK: 'EGBCAHIK', // Annex C option 404
  ABCEGHIL: 'EGBCAHLI', // Annex C option 403
  ABCEGHJK: 'HJBCAGEK', // Annex C option 402
  ABCEGHJL: 'HJBCAGLE', // Annex C option 401
  ABCEGHKL: 'EGBCAHLK', // Annex C option 400
  ABCEGIJK: 'EJBCAGIK', // Annex C option 399
  ABCEGIJL: 'EJBCAGLI', // Annex C option 398
  ABCEGIKL: 'EGBAICLK', // Annex C option 397
  ABCEGJKL: 'EJBCAGLK', // Annex C option 396
  ABCEHIJK: 'EJBCAHIK', // Annex C option 395
  ABCEHIJL: 'EJBCAHLI', // Annex C option 394
  ABCEHIKL: 'EIBCAHLK', // Annex C option 393
  ABCEHJKL: 'EJBCAHLK', // Annex C option 392
  ABCEIJKL: 'EJBAICLK', // Annex C option 391
  ABCFGHIJ: 'HGBCAFIJ', // Annex C option 390
  ABCFGHIK: 'HGBCAFIK', // Annex C option 389
  ABCFGHIL: 'HGBCAFLI', // Annex C option 388
  ABCFGHJK: 'HGBCAFJK', // Annex C option 387
  ABCFGHJL: 'HGBCAFLJ', // Annex C option 386
  ABCFGHKL: 'HGBCAFLK', // Annex C option 385
  ABCFGIJK: 'CJBFAGIK', // Annex C option 384
  ABCFGIJL: 'CJBFAGLI', // Annex C option 383
  ABCFGIKL: 'IGBCAFLK', // Annex C option 382
  ABCFGJKL: 'CJBFAGLK', // Annex C option 381
  ABCFHIJK: 'HJBCAFIK', // Annex C option 380
  ABCFHIJL: 'HJBCAFLI', // Annex C option 379
  ABCFHIKL: 'HIBCAFLK', // Annex C option 378
  ABCFHJKL: 'HJBCAFLK', // Annex C option 377
  ABCFIJKL: 'IJBCAFLK', // Annex C option 376
  ABCGHIJK: 'HJBCAGIK', // Annex C option 375
  ABCGHIJL: 'HJBCAGLI', // Annex C option 374
  ABCGHIKL: 'IGBCAHLK', // Annex C option 373
  ABCGHJKL: 'HJBCAGLK', // Annex C option 372
  ABCGIJKL: 'IJBCAGLK', // Annex C option 371
  ABCHIJKL: 'IJBCAHLK', // Annex C option 370
  ABDEFGHI: 'HGBDAFEI', // Annex C option 369
  ABDEFGHJ: 'HGBDAFEJ', // Annex C option 368
  ABDEFGHK: 'HGBDAFEK', // Annex C option 367
  ABDEFGHL: 'HGBDAFLE', // Annex C option 366
  ABDEFGIJ: 'EGBDAFIJ', // Annex C option 365
  ABDEFGIK: 'EGBDAFIK', // Annex C option 364
  ABDEFGIL: 'EGBDAFLI', // Annex C option 363
  ABDEFGJK: 'EGBDAFJK', // Annex C option 362
  ABDEFGJL: 'EGBDAFLJ', // Annex C option 361
  ABDEFGKL: 'EGBDAFLK', // Annex C option 360
  ABDEFHIJ: 'HJBDAFEI', // Annex C option 359
  ABDEFHIK: 'HEBDAFIK', // Annex C option 358
  ABDEFHIL: 'HEBDAFLI', // Annex C option 357
  ABDEFHJK: 'HJBDAFEK', // Annex C option 356
  ABDEFHJL: 'HJBDAFLE', // Annex C option 355
  ABDEFHKL: 'HEBDAFLK', // Annex C option 354
  ABDEFIJK: 'EJBDAFIK', // Annex C option 353
  ABDEFIJL: 'EJBDAFLI', // Annex C option 352
  ABDEFIKL: 'EIBDAFLK', // Annex C option 351
  ABDEFJKL: 'EJBDAFLK', // Annex C option 350
  ABDEGHIJ: 'HJBDAGEI', // Annex C option 349
  ABDEGHIK: 'EGBDAHIK', // Annex C option 348
  ABDEGHIL: 'EGBDAHLI', // Annex C option 347
  ABDEGHJK: 'HJBDAGEK', // Annex C option 346
  ABDEGHJL: 'HJBDAGLE', // Annex C option 345
  ABDEGHKL: 'EGBDAHLK', // Annex C option 344
  ABDEGIJK: 'EJBDAGIK', // Annex C option 343
  ABDEGIJL: 'EJBDAGLI', // Annex C option 342
  ABDEGIKL: 'EGBAIDLK', // Annex C option 341
  ABDEGJKL: 'EJBDAGLK', // Annex C option 340
  ABDEHIJK: 'EJBDAHIK', // Annex C option 339
  ABDEHIJL: 'EJBDAHLI', // Annex C option 338
  ABDEHIKL: 'EIBDAHLK', // Annex C option 337
  ABDEHJKL: 'EJBDAHLK', // Annex C option 336
  ABDEIJKL: 'EJBAIDLK', // Annex C option 335
  ABDFGHIJ: 'HGBDAFIJ', // Annex C option 334
  ABDFGHIK: 'HGBDAFIK', // Annex C option 333
  ABDFGHIL: 'HGBDAFLI', // Annex C option 332
  ABDFGHJK: 'HGBDAFJK', // Annex C option 331
  ABDFGHJL: 'HGBDAFLJ', // Annex C option 330
  ABDFGHKL: 'HGBDAFLK', // Annex C option 329
  ABDFGIJK: 'FJBDAGIK', // Annex C option 328
  ABDFGIJL: 'FJBDAGLI', // Annex C option 327
  ABDFGIKL: 'IGBDAFLK', // Annex C option 326
  ABDFGJKL: 'FJBDAGLK', // Annex C option 325
  ABDFHIJK: 'HJBDAFIK', // Annex C option 324
  ABDFHIJL: 'HJBDAFLI', // Annex C option 323
  ABDFHIKL: 'HIBDAFLK', // Annex C option 322
  ABDFHJKL: 'HJBDAFLK', // Annex C option 321
  ABDFIJKL: 'IJBDAFLK', // Annex C option 320
  ABDGHIJK: 'HJBDAGIK', // Annex C option 319
  ABDGHIJL: 'HJBDAGLI', // Annex C option 318
  ABDGHIKL: 'IGBDAHLK', // Annex C option 317
  ABDGHJKL: 'HJBDAGLK', // Annex C option 316
  ABDGIJKL: 'IJBDAGLK', // Annex C option 315
  ABDHIJKL: 'IJBDAHLK', // Annex C option 314
  ABEFGHIJ: 'HJBFAGEI', // Annex C option 313
  ABEFGHIK: 'EGBFAHIK', // Annex C option 312
  ABEFGHIL: 'EGBFAHLI', // Annex C option 311
  ABEFGHJK: 'HJBFAGEK', // Annex C option 310
  ABEFGHJL: 'HJBFAGLE', // Annex C option 309
  ABEFGHKL: 'EGBFAHLK', // Annex C option 308
  ABEFGIJK: 'EJBFAGIK', // Annex C option 307
  ABEFGIJL: 'EJBFAGLI', // Annex C option 306
  ABEFGIKL: 'EGBAIFLK', // Annex C option 305
  ABEFGJKL: 'EJBFAGLK', // Annex C option 304
  ABEFHIJK: 'EJBFAHIK', // Annex C option 303
  ABEFHIJL: 'EJBFAHLI', // Annex C option 302
  ABEFHIKL: 'EIBFAHLK', // Annex C option 301
  ABEFHJKL: 'EJBFAHLK', // Annex C option 300
  ABEFIJKL: 'EJBAIFLK', // Annex C option 299
  ABEGHIJK: 'EJBAHGIK', // Annex C option 298
  ABEGHIJL: 'EJBAHGLI', // Annex C option 297
  ABEGHIKL: 'EGBAIHLK', // Annex C option 296
  ABEGHJKL: 'EJBAHGLK', // Annex C option 295
  ABEGIJKL: 'EJBAIGLK', // Annex C option 294
  ABEHIJKL: 'EJBAIHLK', // Annex C option 293
  ABFGHIJK: 'HJBFAGIK', // Annex C option 292
  ABFGHIJL: 'HJBFAGLI', // Annex C option 291
  ABFGHIKL: 'HGBAIFLK', // Annex C option 290
  ABFGHJKL: 'HJBFAGLK', // Annex C option 289
  ABFGIJKL: 'IJBFAGLK', // Annex C option 288
  ABFHIJKL: 'HJBAIFLK', // Annex C option 287
  ABGHIJKL: 'HJBAIGLK', // Annex C option 286
  ACDEFGHI: 'HGECAFDI', // Annex C option 285
  ACDEFGHJ: 'HGJCAFDE', // Annex C option 284
  ACDEFGHK: 'HGECAFDK', // Annex C option 283
  ACDEFGHL: 'HGFCADLE', // Annex C option 282
  ACDEFGIJ: 'CGJDAFEI', // Annex C option 281
  ACDEFGIK: 'CGEDAFIK', // Annex C option 280
  ACDEFGIL: 'CGEDAFLI', // Annex C option 279
  ACDEFGJK: 'CGJDAFEK', // Annex C option 278
  ACDEFGJL: 'CGJDAFLE', // Annex C option 277
  ACDEFGKL: 'CGEDAFLK', // Annex C option 276
  ACDEFHIJ: 'HJECAFDI', // Annex C option 275
  ACDEFHIK: 'HEFCADIK', // Annex C option 274
  ACDEFHIL: 'HEFCADLI', // Annex C option 273
  ACDEFHJK: 'HJECAFDK', // Annex C option 272
  ACDEFHJL: 'HJFCADLE', // Annex C option 271
  ACDEFHKL: 'HEFCADLK', // Annex C option 270
  ACDEFIJK: 'CJEDAFIK', // Annex C option 269
  ACDEFIJL: 'CJEDAFLI', // Annex C option 268
  ACDEFIKL: 'CEIDAFLK', // Annex C option 267
  ACDEFJKL: 'CJEDAFLK', // Annex C option 266
  ACDEGHIJ: 'HGJCADEI', // Annex C option 265
  ACDEGHIK: 'HGECADIK', // Annex C option 264
  ACDEGHIL: 'HGECADLI', // Annex C option 263
  ACDEGHJK: 'HGJCADEK', // Annex C option 262
  ACDEGHJL: 'HGJCADLE', // Annex C option 261
  ACDEGHKL: 'HGECADLK', // Annex C option 260
  ACDEGIJK: 'EGJCADIK', // Annex C option 259
  ACDEGIJL: 'EGJCADLI', // Annex C option 258
  ACDEGIKL: 'EGICADLK', // Annex C option 257
  ACDEGJKL: 'EGJCADLK', // Annex C option 256
  ACDEHIJK: 'HJECADIK', // Annex C option 255
  ACDEHIJL: 'HJECADLI', // Annex C option 254
  ACDEHIKL: 'HEICADLK', // Annex C option 253
  ACDEHJKL: 'HJECADLK', // Annex C option 252
  ACDEIJKL: 'EJICADLK', // Annex C option 251
  ACDFGHIJ: 'HGJCAFDI', // Annex C option 250
  ACDFGHIK: 'HGFCADIK', // Annex C option 249
  ACDFGHIL: 'HGFCADLI', // Annex C option 248
  ACDFGHJK: 'HGJCAFDK', // Annex C option 247
  ACDFGHJL: 'CGJDAFLH', // Annex C option 246
  ACDFGHKL: 'HGFCADLK', // Annex C option 245
  ACDFGIJK: 'CGJDAFIK', // Annex C option 244
  ACDFGIJL: 'CGJDAFLI', // Annex C option 243
  ACDFGIKL: 'CGIDAFLK', // Annex C option 242
  ACDFGJKL: 'CGJDAFLK', // Annex C option 241
  ACDFHIJK: 'HJFCADIK', // Annex C option 240
  ACDFHIJL: 'HJFCADLI', // Annex C option 239
  ACDFHIKL: 'HFICADLK', // Annex C option 238
  ACDFHJKL: 'HJFCADLK', // Annex C option 237
  ACDFIJKL: 'CJIDAFLK', // Annex C option 236
  ACDGHIJK: 'HGJCADIK', // Annex C option 235
  ACDGHIJL: 'HGJCADLI', // Annex C option 234
  ACDGHIKL: 'HGICADLK', // Annex C option 233
  ACDGHJKL: 'HGJCADLK', // Annex C option 232
  ACDGIJKL: 'IGJCADLK', // Annex C option 231
  ACDHIJKL: 'HJICADLK', // Annex C option 230
  ACEFGHIJ: 'HGJCAFEI', // Annex C option 229
  ACEFGHIK: 'HGECAFIK', // Annex C option 228
  ACEFGHIL: 'HGECAFLI', // Annex C option 227
  ACEFGHJK: 'HGJCAFEK', // Annex C option 226
  ACEFGHJL: 'HGJCAFLE', // Annex C option 225
  ACEFGHKL: 'HGECAFLK', // Annex C option 224
  ACEFGIJK: 'EGJCAFIK', // Annex C option 223
  ACEFGIJL: 'EGJCAFLI', // Annex C option 222
  ACEFGIKL: 'EGICAFLK', // Annex C option 221
  ACEFGJKL: 'EGJCAFLK', // Annex C option 220
  ACEFHIJK: 'HJECAFIK', // Annex C option 219
  ACEFHIJL: 'HJECAFLI', // Annex C option 218
  ACEFHIKL: 'HEICAFLK', // Annex C option 217
  ACEFHJKL: 'HJECAFLK', // Annex C option 216
  ACEFIJKL: 'EJICAFLK', // Annex C option 215
  ACEGHIJK: 'EGJCAHIK', // Annex C option 214
  ACEGHIJL: 'EGJCAHLI', // Annex C option 213
  ACEGHIKL: 'EGICAHLK', // Annex C option 212
  ACEGHJKL: 'EGJCAHLK', // Annex C option 211
  ACEGIJKL: 'EJICAGLK', // Annex C option 210
  ACEHIJKL: 'EJICAHLK', // Annex C option 209
  ACFGHIJK: 'HGJCAFIK', // Annex C option 208
  ACFGHIJL: 'HGJCAFLI', // Annex C option 207
  ACFGHIKL: 'HGICAFLK', // Annex C option 206
  ACFGHJKL: 'HGJCAFLK', // Annex C option 205
  ACFGIJKL: 'IGJCAFLK', // Annex C option 204
  ACFHIJKL: 'HJICAFLK', // Annex C option 203
  ACGHIJKL: 'HJICAGLK', // Annex C option 202
  ADEFGHIJ: 'HGJDAFEI', // Annex C option 201
  ADEFGHIK: 'HGEDAFIK', // Annex C option 200
  ADEFGHIL: 'HGEDAFLI', // Annex C option 199
  ADEFGHJK: 'HGJDAFEK', // Annex C option 198
  ADEFGHJL: 'HGJDAFLE', // Annex C option 197
  ADEFGHKL: 'HGEDAFLK', // Annex C option 196
  ADEFGIJK: 'EGJDAFIK', // Annex C option 195
  ADEFGIJL: 'EGJDAFLI', // Annex C option 194
  ADEFGIKL: 'EGIDAFLK', // Annex C option 193
  ADEFGJKL: 'EGJDAFLK', // Annex C option 192
  ADEFHIJK: 'HJEDAFIK', // Annex C option 191
  ADEFHIJL: 'HJEDAFLI', // Annex C option 190
  ADEFHIKL: 'HEIDAFLK', // Annex C option 189
  ADEFHJKL: 'HJEDAFLK', // Annex C option 188
  ADEFIJKL: 'EJIDAFLK', // Annex C option 187
  ADEGHIJK: 'EGJDAHIK', // Annex C option 186
  ADEGHIJL: 'EGJDAHLI', // Annex C option 185
  ADEGHIKL: 'EGIDAHLK', // Annex C option 184
  ADEGHJKL: 'EGJDAHLK', // Annex C option 183
  ADEGIJKL: 'EJIDAGLK', // Annex C option 182
  ADEHIJKL: 'EJIDAHLK', // Annex C option 181
  ADFGHIJK: 'HGJDAFIK', // Annex C option 180
  ADFGHIJL: 'HGJDAFLI', // Annex C option 179
  ADFGHIKL: 'HGIDAFLK', // Annex C option 178
  ADFGHJKL: 'HGJDAFLK', // Annex C option 177
  ADFGIJKL: 'IGJDAFLK', // Annex C option 176
  ADFHIJKL: 'HJIDAFLK', // Annex C option 175
  ADGHIJKL: 'HJIDAGLK', // Annex C option 174
  AEFGHIJK: 'EGJFAHIK', // Annex C option 173
  AEFGHIJL: 'EGJFAHLI', // Annex C option 172
  AEFGHIKL: 'EGIFAHLK', // Annex C option 171
  AEFGHJKL: 'EGJFAHLK', // Annex C option 170
  AEFGIJKL: 'EJIFAGLK', // Annex C option 169
  AEFHIJKL: 'EJIFAHLK', // Annex C option 168
  AEGHIJKL: 'EJIAHGLK', // Annex C option 167
  AFGHIJKL: 'HJIFAGLK', // Annex C option 166
  BCDEFGHI: 'CGBDHFEI', // Annex C option 165
  BCDEFGHJ: 'HGBCJFDE', // Annex C option 164
  BCDEFGHK: 'CGBDHFEK', // Annex C option 163
  BCDEFGHL: 'CGBDHFLE', // Annex C option 162
  BCDEFGIJ: 'CGBDJFEI', // Annex C option 161
  BCDEFGIK: 'CGBDEFIK', // Annex C option 160
  BCDEFGIL: 'CGBDEFLI', // Annex C option 159
  BCDEFGJK: 'CGBDJFEK', // Annex C option 158
  BCDEFGJL: 'CGBDJFLE', // Annex C option 157
  BCDEFGKL: 'CGBDEFLK', // Annex C option 156
  BCDEFHIJ: 'CJBDHFEI', // Annex C option 155
  BCDEFHIK: 'CEBDHFIK', // Annex C option 154
  BCDEFHIL: 'CEBDHFLI', // Annex C option 153
  BCDEFHJK: 'CJBDHFEK', // Annex C option 152
  BCDEFHJL: 'CJBDHFLE', // Annex C option 151
  BCDEFHKL: 'CEBDHFLK', // Annex C option 150
  BCDEFIJK: 'CJBDEFIK', // Annex C option 149
  BCDEFIJL: 'CJBDEFLI', // Annex C option 148
  BCDEFIKL: 'CEBDIFLK', // Annex C option 147
  BCDEFJKL: 'CJBDEFLK', // Annex C option 146
  BCDEGHIJ: 'HGBCJDEI', // Annex C option 145
  BCDEGHIK: 'EGBCHDIK', // Annex C option 144
  BCDEGHIL: 'EGBCHDLI', // Annex C option 143
  BCDEGHJK: 'HGBCJDEK', // Annex C option 142
  BCDEGHJL: 'HGBCJDLE', // Annex C option 141
  BCDEGHKL: 'EGBCHDLK', // Annex C option 140
  BCDEGIJK: 'EGBCJDIK', // Annex C option 139
  BCDEGIJL: 'EGBCJDLI', // Annex C option 138
  BCDEGIKL: 'EGBCIDLK', // Annex C option 137
  BCDEGJKL: 'EGBCJDLK', // Annex C option 136
  BCDEHIJK: 'EJBCHDIK', // Annex C option 135
  BCDEHIJL: 'EJBCHDLI', // Annex C option 134
  BCDEHIKL: 'EIBCHDLK', // Annex C option 133
  BCDEHJKL: 'EJBCHDLK', // Annex C option 132
  BCDEIJKL: 'EJBCIDLK', // Annex C option 131
  BCDFGHIJ: 'HGBCJFDI', // Annex C option 130
  BCDFGHIK: 'CGBDHFIK', // Annex C option 129
  BCDFGHIL: 'CGBDHFLI', // Annex C option 128
  BCDFGHJK: 'HGBCJFDK', // Annex C option 127
  BCDFGHJL: 'CGBDHFLJ', // Annex C option 126
  BCDFGHKL: 'CGBDHFLK', // Annex C option 125
  BCDFGIJK: 'CGBDJFIK', // Annex C option 124
  BCDFGIJL: 'CGBDJFLI', // Annex C option 123
  BCDFGIKL: 'CGBDIFLK', // Annex C option 122
  BCDFGJKL: 'CGBDJFLK', // Annex C option 121
  BCDFHIJK: 'CJBDHFIK', // Annex C option 120
  BCDFHIJL: 'CJBDHFLI', // Annex C option 119
  BCDFHIKL: 'CIBDHFLK', // Annex C option 118
  BCDFHJKL: 'CJBDHFLK', // Annex C option 117
  BCDFIJKL: 'CJBDIFLK', // Annex C option 116
  BCDGHIJK: 'HGBCJDIK', // Annex C option 115
  BCDGHIJL: 'HGBCJDLI', // Annex C option 114
  BCDGHIKL: 'HGBCIDLK', // Annex C option 113
  BCDGHJKL: 'HGBCJDLK', // Annex C option 112
  BCDGIJKL: 'IGBCJDLK', // Annex C option 111
  BCDHIJKL: 'HJBCIDLK', // Annex C option 110
  BCEFGHIJ: 'HGBCJFEI', // Annex C option 109
  BCEFGHIK: 'EGBCHFIK', // Annex C option 108
  BCEFGHIL: 'EGBCHFLI', // Annex C option 107
  BCEFGHJK: 'HGBCJFEK', // Annex C option 106
  BCEFGHJL: 'HGBCJFLE', // Annex C option 105
  BCEFGHKL: 'EGBCHFLK', // Annex C option 104
  BCEFGIJK: 'EGBCJFIK', // Annex C option 103
  BCEFGIJL: 'EGBCJFLI', // Annex C option 102
  BCEFGIKL: 'EGBCIFLK', // Annex C option 101
  BCEFGJKL: 'EGBCJFLK', // Annex C option 100
  BCEFHIJK: 'EJBCHFIK', // Annex C option 99
  BCEFHIJL: 'EJBCHFLI', // Annex C option 98
  BCEFHIKL: 'EIBCHFLK', // Annex C option 97
  BCEFHJKL: 'EJBCHFLK', // Annex C option 96
  BCEFIJKL: 'EJBCIFLK', // Annex C option 95
  BCEGHIJK: 'EJBCHGIK', // Annex C option 94
  BCEGHIJL: 'EJBCHGLI', // Annex C option 93
  BCEGHIKL: 'EGBCIHLK', // Annex C option 92
  BCEGHJKL: 'EJBCHGLK', // Annex C option 91
  BCEGIJKL: 'EJBCIGLK', // Annex C option 90
  BCEHIJKL: 'EJBCIHLK', // Annex C option 89
  BCFGHIJK: 'HGBCJFIK', // Annex C option 88
  BCFGHIJL: 'HGBCJFLI', // Annex C option 87
  BCFGHIKL: 'HGBCIFLK', // Annex C option 86
  BCFGHJKL: 'HGBCJFLK', // Annex C option 85
  BCFGIJKL: 'IGBCJFLK', // Annex C option 84
  BCFHIJKL: 'HJBCIFLK', // Annex C option 83
  BCGHIJKL: 'HJBCIGLK', // Annex C option 82
  BDEFGHIJ: 'HGBDJFEI', // Annex C option 81
  BDEFGHIK: 'EGBDHFIK', // Annex C option 80
  BDEFGHIL: 'EGBDHFLI', // Annex C option 79
  BDEFGHJK: 'HGBDJFEK', // Annex C option 78
  BDEFGHJL: 'HGBDJFLE', // Annex C option 77
  BDEFGHKL: 'EGBDHFLK', // Annex C option 76
  BDEFGIJK: 'EGBDJFIK', // Annex C option 75
  BDEFGIJL: 'EGBDJFLI', // Annex C option 74
  BDEFGIKL: 'EGBDIFLK', // Annex C option 73
  BDEFGJKL: 'EGBDJFLK', // Annex C option 72
  BDEFHIJK: 'EJBDHFIK', // Annex C option 71
  BDEFHIJL: 'EJBDHFLI', // Annex C option 70
  BDEFHIKL: 'EIBDHFLK', // Annex C option 69
  BDEFHJKL: 'EJBDHFLK', // Annex C option 68
  BDEFIJKL: 'EJBDIFLK', // Annex C option 67
  BDEGHIJK: 'EJBDHGIK', // Annex C option 66
  BDEGHIJL: 'EJBDHGLI', // Annex C option 65
  BDEGHIKL: 'EGBDIHLK', // Annex C option 64
  BDEGHJKL: 'EJBDHGLK', // Annex C option 63
  BDEGIJKL: 'EJBDIGLK', // Annex C option 62
  BDEHIJKL: 'EJBDIHLK', // Annex C option 61
  BDFGHIJK: 'HGBDJFIK', // Annex C option 60
  BDFGHIJL: 'HGBDJFLI', // Annex C option 59
  BDFGHIKL: 'HGBDIFLK', // Annex C option 58
  BDFGHJKL: 'HGBDJFLK', // Annex C option 57
  BDFGIJKL: 'IGBDJFLK', // Annex C option 56
  BDFHIJKL: 'HJBDIFLK', // Annex C option 55
  BDGHIJKL: 'HJBDIGLK', // Annex C option 54
  BEFGHIJK: 'EJBFHGIK', // Annex C option 53
  BEFGHIJL: 'EJBFHGLI', // Annex C option 52
  BEFGHIKL: 'EGBFIHLK', // Annex C option 51
  BEFGHJKL: 'EJBFHGLK', // Annex C option 50
  BEFGIJKL: 'EJBFIGLK', // Annex C option 49
  BEFHIJKL: 'EJBFIHLK', // Annex C option 48
  BEGHIJKL: 'EJIBHGLK', // Annex C option 47
  BFGHIJKL: 'HJBFIGLK', // Annex C option 46
  CDEFGHIJ: 'CGJDHFEI', // Annex C option 45
  CDEFGHIK: 'CGEDHFIK', // Annex C option 44
  CDEFGHIL: 'CGEDHFLI', // Annex C option 43
  CDEFGHJK: 'CGJDHFEK', // Annex C option 42
  CDEFGHJL: 'CGJDHFLE', // Annex C option 41
  CDEFGHKL: 'CGEDHFLK', // Annex C option 40
  CDEFGIJK: 'CGEDJFIK', // Annex C option 39
  CDEFGIJL: 'CGEDJFLI', // Annex C option 38
  CDEFGIKL: 'CGEDIFLK', // Annex C option 37
  CDEFGJKL: 'CGEDJFLK', // Annex C option 36
  CDEFHIJK: 'CJEDHFIK', // Annex C option 35
  CDEFHIJL: 'CJEDHFLI', // Annex C option 34
  CDEFHIKL: 'CEIDHFLK', // Annex C option 33
  CDEFHJKL: 'CJEDHFLK', // Annex C option 32
  CDEFIJKL: 'CJEDIFLK', // Annex C option 31
  CDEGHIJK: 'EGJCHDIK', // Annex C option 30
  CDEGHIJL: 'EGJCHDLI', // Annex C option 29
  CDEGHIKL: 'EGICHDLK', // Annex C option 28
  CDEGHJKL: 'EGJCHDLK', // Annex C option 27
  CDEGIJKL: 'EGICJDLK', // Annex C option 26
  CDEHIJKL: 'EJICHDLK', // Annex C option 25
  CDFGHIJK: 'CGJDHFIK', // Annex C option 24
  CDFGHIJL: 'CGJDHFLI', // Annex C option 23
  CDFGHIKL: 'CGIDHFLK', // Annex C option 22
  CDFGHJKL: 'CGJDHFLK', // Annex C option 21
  CDFGIJKL: 'CGIDJFLK', // Annex C option 20
  CDFHIJKL: 'CJIDHFLK', // Annex C option 19
  CDGHIJKL: 'HGICJDLK', // Annex C option 18
  CEFGHIJK: 'EGJCHFIK', // Annex C option 17
  CEFGHIJL: 'EGJCHFLI', // Annex C option 16
  CEFGHIKL: 'EGICHFLK', // Annex C option 15
  CEFGHJKL: 'EGJCHFLK', // Annex C option 14
  CEFGIJKL: 'EGICJFLK', // Annex C option 13
  CEFHIJKL: 'EJICHFLK', // Annex C option 12
  CEGHIJKL: 'EJICHGLK', // Annex C option 11
  CFGHIJKL: 'HGICJFLK', // Annex C option 10
  DEFGHIJK: 'EGJDHFIK', // Annex C option 9
  DEFGHIJL: 'EGJDHFLI', // Annex C option 8
  DEFGHIKL: 'EGIDHFLK', // Annex C option 7
  DEFGHJKL: 'EGJDHFLK', // Annex C option 6
  DEFGIJKL: 'EGIDJFLK', // Annex C option 5
  DEFHIJKL: 'EJIDHFLK', // Annex C option 4
  DEGHIJKL: 'EJIDHGLK', // Annex C option 3
  DFGHIJKL: 'HGIDJFLK', // Annex C option 2
  EFGHIJKL: 'EJIFHGLK', // Annex C option 1
}
